export interface SeedProvider {
  id: string;
  user_id: string;
  name: string;
  role: string;
  description: string;
  specialties: string;
  service_ids: string[];
  rating: number;
  city: string;
  avatar_url: string;
  photo: string;
  distance: string;
  eta: string;
  created_at: string;
}

export const providers: SeedProvider[] = [
  {
    id: 'lucas-costa',
    user_id: 'seed-user-lucas',
    name: 'Lucas Costa',
    role: 'Eletricista',
    description: 'Técnico especializado em instalações residenciais e soluções elétricas seguras.',
    specialties: 'Instalação de quadros, tomadas, automação residencial e iluminação LED.',
    service_ids: ['eletricista'],
    rating: 4.96,
    city: 'Vila Mariana',
    avatar_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80',
    photo: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80',
    distance: '1,2 km',
    eta: '9 min',
    created_at: new Date().toISOString(),
  },
  {
    id: 'marina-rodrigues',
    user_id: 'seed-user-marina',
    name: 'Marina Rodrigues',
    role: 'Encanadora',
    description: 'Atendimento de emergência com foco em reparos rápidos e duradouros.',
    specialties: 'Vazamentos, substituição de registros e manutenção de aquecedores.',
    service_ids: ['encanador'],
    rating: 4.88,
    city: 'Pinheiros',
    avatar_url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=200&q=80',
    photo: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=200&q=80',
    distance: '2,4 km',
    eta: '12 min',
    created_at: new Date().toISOString(),
  },
  {
    id: 'rafael-silva',
    user_id: 'seed-user-rafael',
    name: 'Rafael Silva',
    role: 'Pintor',
    description: 'Pintura com acabamento liso e proteção contra áreas úmidas.',
    specialties: 'Pintura interna, selagem e reparo de paredes antes do acabamento.',
    service_ids: ['pintor'],
    rating: 4.94,
    city: 'Moema',
    avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
    photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
    distance: '1,7 km',
    eta: '11 min',
    created_at: new Date().toISOString(),
  },
  {
    id: 'aline-souza',
    user_id: 'seed-user-aline',
    name: 'Aline Souza',
    role: 'Diarista',
    description: 'Diarista com foco em casas e apartamentos, limpeza detalhada e organização.',
    specialties: 'Limpeza diária, pós-festa e higienização de superfícies delicadas.',
    service_ids: ['diarista', 'limpeza-pos-obra'],
    rating: 4.85,
    city: 'Vila Madalena',
    avatar_url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=200&q=80',
    photo: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=200&q=80',
    distance: '1,0 km',
    eta: '8 min',
    created_at: new Date().toISOString(),
  },
  {
    id: 'bruno-oliveira',
    user_id: 'seed-user-bruno',
    name: 'Bruno Oliveira',
    role: 'Montador de móveis',
    description: 'Montagem de móveis com garantia de alinhamento e ajuste perfeito.',
    specialties: 'Armários, racks, estantes e móveis planejados.',
    service_ids: ['montagem', 'marcenaria'],
    rating: 4.91,
    city: 'Itaim Bibi',
    avatar_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80',
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80',
    distance: '3,0 km',
    eta: '14 min',
    created_at: new Date().toISOString(),
  },
  {
    id: 'carla-martins',
    user_id: 'seed-user-carla',
    name: 'Carla Martins',
    role: 'Técnica de ar-condicionado',
    description: 'Instalação e manutenção de aparelhos com foco em economia de energia.',
    specialties: 'Limpeza de filtros, recarga de gás e diagnóstico completo.',
    service_ids: ['ar-condicionado'],
    rating: 4.92,
    city: 'Brooklin',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80',
    photo: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80',
    distance: '2,8 km',
    eta: '13 min',
    created_at: new Date().toISOString(),
  },
  {
    id: 'eduardo-rocha',
    user_id: 'seed-user-eduardo',
    name: 'Eduardo Rocha',
    role: 'Chaveiro',
    description: 'Atendimento 24h para abertura de portas e troca de fechaduras.',
    specialties: 'Fechaduras eletrônicas, residenciais e cópia de chaves.',
    service_ids: ['chaveiro'],
    rating: 4.87,
    city: 'Vila Olímpia',
    avatar_url: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=200&q=80',
    photo: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=200&q=80',
    distance: '5,3 km',
    eta: '15 min',
    created_at: new Date().toISOString(),
  },
  {
    id: 'fernanda-lima',
    user_id: 'seed-user-fernanda',
    name: 'Fernanda Lima',
    role: 'Jardinagem',
    description: 'Manutenção de jardins com cuidado de plantas e paisagismo simples.',
    specialties: 'Poda, adubação e instalação de canteiros.',
    service_ids: ['jardinagem'],
    rating: 4.90,
    city: 'Vila Clementino',
    avatar_url: 'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=200&q=80',
    photo: 'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=200&q=80',
    distance: '3,6 km',
    eta: '16 min',
    created_at: new Date().toISOString(),
  },
  {
    id: 'gustavo-pereira',
    user_id: 'seed-user-gustavo',
    name: 'Gustavo Pereira',
    role: 'Limpeza pós-obra',
    description: 'Limpeza técnica após reforma para entregar cada ambiente pronto para uso.',
    specialties: 'Desempoeiramento, remoção de restos e limpeza pesada.',
    service_ids: ['limpeza-pos-obra'],
    rating: 4.83,
    city: 'Vila Madalena',
    avatar_url: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=200&q=80',
    photo: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=200&q=80',
    distance: '2,2 km',
    eta: '12 min',
    created_at: new Date().toISOString(),
  },
];
